MDAnalysis/MDAnalysis.github.io

- _includes/sidebar.html
- blog/index.html
Fixed the following:
- Sidebar currently lists one blog entry per paginated page.
- 'Older'/'Newer' links in blog posts are based off the site's root, instead of `/blog/`
> Fix wrong blog navigation links

- _includes/sidebar.html
Good point @orbeckst. This should do it (notice I now fish directly `site.paginate_path`, which is potentially different from `site.blog/page`).
> Made sidebar blog link check more generic

- _posts/2016-03-19-conda.md
- pages/installation_quick_start.md
Fixes #20 
After merging the build instructions it's time to make the conda build official. Here is the release text for the blog post and the changed quick install instructions.
> Conda (fixes #20)

- _posts/2016-xx-xx-release-0.16.md
A first draft of some paragraphs on Encore and MemoryReader to add to the 0.16.0 release blog post.
> Contributions on Encore and MemoryReader to Blog on 0.16.0 release

- _posts/2017-02-09-CoC.md
The [Code of Conduct](http://www.mdanalysis.org/pages/conduct/) needs to be properly announced so that EVERYONE knows that this is now the basis for our interactions.
- introduction and background for new CoC #34 
- will also be sent to mailing lists
- should also be tweeted 
@MDAnalysis/coredevs please have a look.
> blog post for CoC

- about.md
The scipy paper was added to the citation page, but the about page was still only listing the initial paper.
> Add the scipy paper in the about page

- about.md
- index.md
- fixes #39
- make clear that EVERYTHING is GPL v2 (or later); legally, by including code
under more permissive licenses we also put it under GPLv2 (that's what the GPL does)
but because that code exists under permissive licenses separate from MDA, users
can still use it under that permissive license
> use clearer language for license

- _posts/2017-11-11-release-0.16.0.md
This depends on https://github.com/MDAnalysis/mdanalysis/pull/1290 being merged!
> Use a working example for the aux reader

- README.md
- _config.yml
- _includes/footer.html
- _includes/head.html
- _includes/sidebar.html
- _layouts/default.html
- _posts/2015-12-15-The_benefit_of_social_coding.md
- _posts/2017-03-01-numfocus.md
- _posts/2017-03-02-gsoc2017.md
- _posts/2017-06-03-numfocus-grant.md
- _posts/2018-02-14-gsoc2018.md
- blog/index.html
- closes #73 
- note that this opposes #16
> add Algolia search

- pages/citations.md
The page numbers are now taken from the official bibtex entry. I checked that they match with the pdf.
It could be we need to change this in the *whole* library.
> update scipy citation page numbers

- about.md
- updates as agreed by vote in issue #113 
- name project leadership "MDAnalysis Core Developers"
- update: decisions are made with simple majority
- minor change: link to CoC, rephrased decision making procedure
> update governance section in About

- _posts/2020-02-22-gsoc2020.md
> draft GSOC 2020 post

- index.md
- pages/privacy.md
Fix #129 
- adds a normal page with the privacy policy (which shows up in the menu and not in any special place)
- links to https://numfocus.org/privacy-policy, which legally governs all MDAnalysis sites; this is based on advice from NumFOCUS
- explain what information we gather (very little thanks to the removal of Google Analytics #131) and what our 3rd party providers are
> privacy policy

- pages/privacy.md
These are NumFOCUS' wording suggestions for referring to our privacy policy. This is tricky because legally we are the same entity but we still need to make it clear that MDAnalysis has some autonomy with data processing. I hope this sounds okay. 😄
> NF edits to privacy.md

- about.md
As per discussion on the business list: a "simple majority" is half of the votes cast as described in link to https://en.wikipedia.org/wiki/Majority#Majority_vote. This PR just adds the link.
Please @MDAnalysis/coredevs have a look/change.
> clarify "simple majority"

- _config.yml
- _posts/2020-02-22-gsoc2020.md
When I moved the quickstart guide to a top-level URL (see https://github.com/MDAnalysis/UserGuide/issues/109), I inadvertently broke the links on the website (see https://github.com/MDAnalysis/mdanalysis/issues/3090). This PR fixes that.
> Update links to quickstart

- pages/used-by.md
Hi,
I'd like to add [LiPyphilic](https://lipyphilic.readthedocs.io/en/latest/) to the "used by" page. It's a Python package for analysing MD simulations of lipid membranes, and is based on MDAnalysis. It's essentially a bunch of analysis tools that each use the MDAnalysis base analysis class, plus there are a couple of trajectory transformations.
> Add LiPyphilic to used-by.md

- _posts/2021-05-02-release-1.x.x.md
- CHANGELOG entry was wrong for PDBWriter chain writing: we now correctly write the LAST character of the segid as chainid
- https://github.com/MDAnalysis/mdanalysis/pull/2478#issuecomment-832824399
> fixed blogpost

- Gemfile
I had to add the webrick gem to build #189  in ruby 3.0.
> Add webrick gem

- _config.yml
- public/css/hyde.css
- sitemapindex.xml
- change sidebar to RTD dark gray (match user guide and docs, see #135)
- update version information to 2.0.0 (in particular make sitemap point to the 2.0.0 docs!!)
> style update

- sitemapindex.xml
fixes #200 
related to #199 
I have added the distopia sitemap to the master sitemap, however like `PyTNG` it doesn't seem to appear on a search.
@orbeckst any ideas?
> Add distopia to sitemap

- about.md
- result of 2021 role call
- updated list of Core Devs
- add new list of EmCDs
- added subsections for CDs and EmCDs with short summary of function
(based on the passed proposal for EmCDs)
- renamed "Decision Making Process" to "Decision Making Process and Membership"
- added 3rd item to "Decision Making Process and Membership" on CD opt-in and EmCD
> update Core Developers and EmCDs

- _config.yml
- _includes/footer.html
- _includes/head.html
- _includes/sidebar.html
- public/css/search.css
- use new appId and key (from UI)
- use newer integration with docs from https://github.com/algolia/docsearch
- new CSS
- new JS
- closes #211
> update algolia to new index and search box

- about.md
@micaela-matta informed the current Core Devs that she returns to Core Dev status from Emeritus Core Dev.
In line with our governance rules she is herewith reinstated to Core Developer.
> re-instated Micaela Matta as Core Dev

- _posts/2022-06-27-applem1packages.md
Announce that we have working M1 packages. 
Updates the 2.2 release blog (which stated that we *didn't* have M1)
> short blog for M1 packages

- _posts/2022-11-07-relicensing.md
I always forget it's meant to be non-capital letters...
> Fix internal links for license blog post

- _posts/2022-11-07-relicensing.md
> more license name fixes

- README.md
Update to the README: From hackathon: How to build the docs locally using a docker container because somehow all the ruby packages live in the 5th circle of dependency hell.
> add instructions for using Docker for local jekyll build

- about.md
As agreed on in the last core-devs meeting, I made a very generic feedback form and added it to the "About" page on the site. We could possibly also make it a separate page so it appears on the sidebar -- right now it's a little buried.
The form is linked as is -- it's very open-ended and generic, and totally anonymous. Not sure if we want to collect emails to have *some* accountability and for some means of following-up?
> Add feedback form

- about.md
As decided by vote and ratified at business meeting on 2023-12-08: "CoreDev status required to be PI on an MDAnalysis grant; co-PIs do not have to be CoreDev."
> update governance: PIs must be CoreDevs

- about.md
Logos were showing in line with the name if the _next_ organization, so I have moved them above the text for each org.
> Move funding logos to fix formatting

- about.md
In combination with previous PRs, closes https://github.com/MDAnalysis/MDAnalysis.github.io/issues/300.
In this PR, 2 additional people are listed as [MDAnalysis Core Developers](https://www.mdanalysis.org/about/#mdanalysis-core-developers) on the website's **About** page:
- jennaswa (core dev privileges granted to PCM as decided by a vote at 2024-12-18 business meeting)
- yuxuanzhuang (elected by a vote at 2024-02-26 business meeting; accepted invitation 2024-03-02)
> Add jennaswa and yuxuanzhuang to Core Devs list on about page

- index.md
Made minor updates to the "[Participating](https://www.mdanalysis.org/#participating)" section of the MDAnalysis home page, including:
- Change GitHub Discussions _mailing list_ to _forum_
- Add links to MDAnalysis YouTube and Bluesky profiles
- Promote UGM 2024
> Update 'participating' section on home page

- about.md
Closes #363 
This PR
- adds a mission statement under **About the MDAnalysis Project** to the top of the [About](https://www.mdanalysis.org/about/) page ("version 1" draft, as agreed at Business Meeting on 2024-02-26)
- asks @MDAnalysis/coredevs to review and alter the language as needed
- invites anyone interested in the direction that MDAnalysis takes to comment
- asks @MDAnalysis/coredevs to ultimately approve the final mission statement
This Mission Statement is not set in stone and should be periodically revisited and updated. However, it seems unlikely that such updates will happen frequently so you should consider this language to have a long half-life (i.e., it will guide decisions for years to come).
> add mission statement to About

- _posts/2024-04-24-ASUworkshop.md
The title is not showing up properly for the workshop blog post - I suspect having a colon in the title upset it; replaced that. Also adjusting the image alignment while I'm here.
> Fix workshop post

- _posts/2024-05-30-ccpbiosim-industry-talk.md
CCPBioSim now has an event page for @richardjgowers's  talk on June 19: https://www.ccpbiosim.ac.uk/events/upcoming-events/eventdetail/122/-/industry-talk-mdanalysis.
It'd be great to get a blog post out so that we can spread the news on our socials and encourage people to register.
> Draft blog post to advertise Richard's CCPBioSim talk

- about.md
Updating the 'Funding' section to include the github handles for our [2024 GSoC and Outreachy contributors](https://www.mdanalysis.org/2024/05/27/gsoc-outreachy-students/).
> Add 2024 GSoC and Outreachy contributors to about.md

- _data/team/roles/code_of_conduct.yml
- _includes/team_table_member_cell.html
This PR adds markdown support for links, etc. as necessary for #402 
Please note that the YAML must still be valid (as shown in the example), so a link must be encased in quotes to be interpreted as a string item of a list.
> Add Markdown support for team members

- _posts/2024-11-22-release-2.8.0.md
Blog post with
- big news
- important changes
- contributors
> release 2.8.0 blog post

- index.md
The landing page is still encouraging registration for UGM 2024, which is now 3 months in the past. This PR updates our top-level page.
> remove UGM 2024 from landing page

- _data/team/roles/code_of_conduct.yml
- _data/team/roles/community_engagement.yml
- _data/team/roles/continuous_integration.yml
- _data/team/roles/core_library_maintenance.yml
- _data/team/roles/documentation.yml
- _data/team/roles/external_liaison.yml
- _data/team/roles/mdakit_registry.yml
- _data/team/roles/non_core_library_maintenance.yml
- _data/team/roles/outreach.yml
- _data/team/roles/project_organization.yml
- _data/team/roles/releases_and_deployment.yaml
- _data/team/roles/relicensing_coordinator.yml
- _data/team/roles/social_media.yml
- _includes/team_table.html
Per the discussion in https://github.com/MDAnalysis/MDAnalysis.github.io/issues/397, the main purpose of this PR is to:
In addition, this would provide a good opportunity to update team members in preparation for our first upcoming [R&R review](https://docs.google.com/document/d/1EcC7Y3pJY9aoB2nSJAo6hMd_55p8su7wHrXohVv-qTI/edit?usp=sharing), as decided in the [Aug 20 business meeting](https://docs.google.com/document/d/1SLS8v1_pxYEYha9_3LqjuGE4Q6DC6SeJ722gNy3iHrU/edit?usp=sharing). Namely:
Thanks!
> Update contact information for Team page

- _data/team/roles/outreach.yml
I propose we include a link to the GSoC wiki page stating who is mentoring for the year in order to acknowledge folks volunteering to mentor/admin. I have included a link to the wiki so that this will be updated when we update things for the GSoC program, but we can also write individual names here if that is preferred (though it will be harder to keep up-to-date imo)
> Credit GSoC mentors in the "mentoring" team

- Gemfile
> Fix FFI version in Gemfile

- _data/team/roles/documentation.yml
As our new Technical Writer for the SDG documentation project, it would be great to officially add @namiroues on the MDAnalysis team page :)
> Teams: Add Namir to documentation team

- _data/team/roles/external_liaison.yml
In the latest round of team reviews, I proposed adding @micaela-matta and @yuxuanzhuang to the External Liaison team based on their past contributions to securing sponsorships for events (MM) and participation in the NF project summit and collabs with other projects (e.g., Molecular Nodes) (YZ).
Additionally, @IAlibay brought up the question of @MDAnalysis/coredevs expectations in terms of reporting back on liaisons (e.g., emails or summaries in other formats after meetings). If there is a desire for this, perhaps it makes sense to add this explicitly as a responsibility.
> Teams: Add Micaela and Yuxuan to external liaison team

- _data/team/roles/core_library_maintenance.yml
From team reviews: The wording of the responsibilities list seems to indicate that the persons on this team are responsible for maintaining the entire ecosystem. It should be made clear that folks that are responsible for a specific sub-part of the ecosystem should be responsible for maintaining them.
> Teams: Clarify that sub-project managers are also responsible for maintenance

- Gemfile
- INSTALL.md
- README.md
- _config.yml
- Gemfile update: ruby >= 2.7 (should now work on Apple silicon and in particular can use ruby 3.x), pinned rdiscount package because of https://github.com/davidfstr/rdiscount/issues/145
- add zoneinfo files for Windows (jekyll docs recommendation)
- add jekyll installation notes in INSTALL (macOS)
- add file exclusion to _config.yml
- updated the config author.url to the team pages (instead of twitter)
> update to ruby >= 2.7, <4

- _config.yml
- _data/team/roles/community_engagement.yml
- _data/team/roles/social_media.yml
Based on our team reviews, I proposed combining the social media and community engagement teams. This PR therefore:
- Incorporates the social media tasks into the community engagement task list
- Removes the social media team
- Adds links to relevant profiles referenced
Note that the following items are up for discussion at the 02-24-24 business meeting, and may influence this PR.
- Whether to keep the MDAnalysis X account. X is currently excluded from the list of profiles in this PR.
- Whether AO is interested in helping to manage content for the socials/blog. If so, we should add her as a team member.
> Teams: Integrate 'social media' into 'community engagement' tasks

- _data/team/roles/releases_and_deployment.yaml
> Fix YAML syntax error in current_members list

- _data/team/roles/mdakit_registry.yml
From team reviews: “Manage helping with MDAKits who need assistance” is an unclear goal, and possibly an unrealistic one as the registry grows. We suggest rephrasing the responsibility to “offer input on MDAKit issues where possible” as a more realistic responsibility.
Relatedly, we will need to develop a post-EOSS4 plan to ensure the registry is maintained.
> Teams: Rephrase task on helping with specific MDAKits

- pages/learning_MDAnalysis.md
> Sdg23 refine 'learning MDAnalysis' page

- index.md
> update landing page

- about.md
- conduct.md
- mission.md
- pages/funding.md
- pages/governance.md
- pages/mission.md
> Refined About, Mission, Governance, and Funding pages

- pages/citations.md
> update citations page

- pages/events.md
- pages/ugm2024.md
> Sdg23 add events page

- index.md
Removed the old "fork me" from the top right corner of the landing page. The image is no longer accessible and it also feels dated.
> remove fork-me

- _data/team/roles/outreach.yml
Our team reviews revealed that the "Teaching materials" and "Workshops and meetings" teams were really one in the same. This PR therefore:
- Incorporates the teaching materials tasks into the workshops and meetings task list
- Removes the teaching materials team
- Proposes adding @richardjgowers and @yuxuanzhuang to the team based on their substantial contributions
- Adds 'identifying sponsors' as an inherent task related to organizing events
Note that processes for archiving workshop materials are up for discussion at the 02-24-24 business meeting, and may influence this PR. Additionally, as NO's work on the SDG docs project will likely touch the teaching material organization, it will likely make sense to add her as a team member as well.
> Teams: Integrate 'teaching materials' into 'workshops and meetings' tasks

- _includes/sidebar.html
The webpage will look like this with this change. (The pages are reordered appropriately in #458).
I am happy to hear suggestions regarding the text and button (if it stays or should be removed) on the landing and funding pages.
> add donation button to the sidebar
