MDAnalysis/MDAnalysis.github.io

_posts/2016-01-16-release-0.13.0.md

I thought we could start adding posts about the releases to the blog now.

Add release blog post

---

_posts/2016-04-26-gsoc.md

This is a first draft of the GSoC announcement post. I will add more information about the BIO from @jdetle and @fiona-naughton when I get it and pictures is you like to have them posted here as well.
The project description could use some work still though.
ping @MDAnalysis/coredevs

create first draft of GSoC project post

---

pages/citations.md

- added Gowers et al 2016 SciPy paper
- request that both MDAnalysis papers are cited
- closes #27

updated MDAnalysis citation

---

pages/conduct.md

See #34 
@orbeckst I'll leave it to you to merge this if you are happy with it.

add CoC page

---

_posts/2017-03-01-numfocus.md

This change aims at showing that the numfocus affiliation is a good news.

Warm up the numfocus announcement

---

_posts/2017-03-01-numfocus.md

The current content is relatively short and to the point. Should we add a little bit about the history of the last year and look for projects that are currently using MDAnalysis as well for this post or some other time?

add numfocus post

---

pages/basic_example.md

Fixes #45
I did not touch the quick segment, and quick atom selectors. Here I just fixed the compatibility issue.

Fix basic example compatibility

---

_posts/2017-06-03-numfocus-grant.md

Mostly a copy from our application. Not sure if we should add other information. Maybe the github project where we list issues for people to help with python 3 support?

start a numfocus grant post

---

_posts/2017-06-03-gsoc-students.md

I kind of forgot to make a blog post about this earlier.
@utkbansal Could you provide us with a short paragraph for your biography? You can have a look what our last students wrote last year about themselves [here](http://www.mdanalysis.org/2016/04/26/gsoc/)

Have a GSoC student post

---

_posts/2018-02-14-gsoc2018.md

new announcement post for gsoc

add gsoc 2018 post

---

_posts/2017-03-02-gsoc2017.md
_posts/2018-02-14-gsoc2018.md

use our own numfocus logo

---

_posts/2018-04-22-release-0.18.0.md

need to add duecredit and Universe.copy examples

started 0.18.0 blog post

---

_posts/2018-04-26-gsoc-students.md

Hey there, I added a short bio and the link to my blog to the GSOC 2018 post.
What do you think?

added bio and blog to GSoC 2018 post

---

_posts/2018-04-26-gsoc-students.md

Modified the bio and updated the link for blog

---

_posts/2018-04-26-gsoc-students.md

- close #70
- added stubs for @ayushsuhane and @davidercruz
- TODO

start GSOC 2018 student blog post

---

pages/basic_example.md

Update basic example to avoid deprecation error

---

_posts/2019-03-04-gsoc2019.md

Blog needed for advertising GSOC 2019 #96

drafted blog post for GSOC 2019

---

_posts/2019-04-20-mdanalysis-as-a-building-block.md
_posts/2019-04-29-mdanalysis-as-a-building-block.md

blog post about projects using MDA

---

.gitignore
about.md
pages/used-by.md

This should be enough to have a static page. I cannot test right now because my bundler installation is broken.

use building block as a static page

---

_posts/2019-05-24-gsoc-students.md

Adds Ninad Bhat bio

---

_posts/2019-05-24-gsoc-students.md

GSoC 2019 Student blog post: Ninad Bhat

---

_posts/2019-08-08-gsod-techwriter.md

- based on material from @lilyminium
- added GSoD logo and @lilyminium GitHub avatar image

GSoD 2019 tech writer blog post

---

_config.yml
_posts/2020-02-14-numfocus-sponsored-project.md
about.md

Fixes #120 
- overview
- link to governance/coredevs
- outlook
- donate button

NumFOCUS Sponsored Project blog post

---

pages/used-by.md

Adds `taurenmd` to the Analysis Tools that use MDAnalysis.

add taurenmd

---

_posts/2020-05-20-gsoc-students.md

- close #127 
- introduce our 3 GSoC students @hmacdope, @cbouy, and @yuxuanzhuang and their projects
- pre-populated photos and bios from public information

GSoC 2020 students

---

_includes/footer.html
_includes/head.html

- fix #131
- Goatcounter stats at https://mdanalysis.goatcounter.com/
- @orbeckst registered the site

replaced Google Analytics with Goatcounter

---

_posts/2020-09-03-final-report-hugo.md

Hi all, my final GSOC report for posting on the blog.

Hugo final GSOC report.

---

_posts/2020-09-10-gsoc2020-final.md

Last GSoC 2020 post, to be referenced in a tweet (today or tomorrow)
> Congratulations to our 3 #GSoC2020 students Yuxuan Zhuang, @cedricbouysset, @HugoMacdermott who sucessfully completed their #GSOC projects https://summerofcode.withgoogle.com/organizations/4891814374408192/ . Read more about them in our blog https://www.mdanalysis.org/blog/

final GSoC 2020 blog post

---

sitemapindex.xml

add pytng sitemap to index

---

pages/used-by.md

Hello,
As @orbeckst suggested in https://github.com/GMPavanLab/Swarm-CG/issues/10, we would gladly be included in the list of MDAnalysis "Used By" software. I took upon me to create a new category, I hope it's fine.

Add Swarm-CG to the list of MDAnalysis "Used By"

---

about.md

Spelling mistake is corrected :-
"scientifc" -> "scientific".

Update ABOUT file.

---

_config.yml

- broaden tag line (not _just_ MD)
- use description from https://numfocus.org/project/mdanalysis

update tagline and description

---

_posts/2021-04-09-prace-workshop.md

Really simple / hastily put together blog post.
Please rewrite as necessary.
Fixes #169

PRACE workshop blog post

---

about.md

add new coredevs

---

_config.yml
_posts/2021-05-02-release-1.x.x.md

Fixes #130 
pinging @MDAnalysis/coredevs 
This is a very rough draft of the 1.x.x release blog post. There's a lot to get done here to get this good to go (sorry this is as much as I have time for atm).
If everyone can pitch in a bit we should be able to get this done quickly. Ideally we want this out for users to read by the end of the day tomorrow.

1.x.x release blog post

---

_posts/2021-05-19-gsoc-students.md

add Orion project link

---

_config.yml

fix #181
Thank you to @demianriccardi

fixed link to UG

---

pages/learning_MDAnalysis.md

- recommend User Guide
- close #147

removed link to old MDAnalysisTutorial

---

_posts/2021-08-22-release-2.0.0.md

Here is an initial draft of the 2.0.0 release.
@MDAnalysis/coredevs please review.

Blog post for the 2.0 release

---

pages/used-by.md

- close  #178
- close marrink-lab/MDVoxelSegmentation#111

add MDVoxelSegmentation to used-by page

---

sitemapindex.xml

- docs: 2.0.0 --> stable
- User Guide: 2.0.0 --> stable

point sitemaps to stable versions

---

pages/learning_MDAnalysis.md

Adding https://www.youtube.com/watch?v=1Wot83DSt4E

add BioExcel video to Learning

---

about.md

Added newly elected Core Devs Hugo and Philip to the official list.
Please approve @MDAnalysis/coredevs

added new CoreDevs

---

_posts/2022-03-02-NF-CDR-Interview-Call.md

This is related to the outreach call text we sent around a couple weeks ago.

NF DEI interview call

---

_posts/2022-03-02-NF-CDR-Interview-Call.md

I think the ":" in the title is causing issues

Fix title in latest blog post

---

_posts/2022-03-07-gsoc2022.md

Please review.
Please do _not_ change file name because I already updated links on the wiki.

Blog GSoC 2022

---

README.md
_posts/2016-01-16-release-0.13.0.md
_posts/2016-02-28-release-0.14.0.md
_posts/2016-03-08-gsoc2016.md
_posts/2016-04-26-gsoc.md
_posts/2016-05-16-release-0.15.0.md
_posts/2016-11-30-Support-for-MMTF.md
_posts/2017-03-02-gsoc2017.md
_posts/2017-04-07-environments.md
_posts/2017-04-10-release-0.16.0.md
_posts/2017-06-04-gsoc-students.md
_posts/2017-06-06-release-0.16.1.md
_posts/2017-06-27-release-0.16.2.md
_posts/2018-02-14-gsoc2018.md
_posts/2018-04-26-gsoc-students.md
_posts/2019-03-04-gsoc2019.md
_posts/2019-05-24-gsoc-students.md
_posts/2020-02-22-gsoc2020.md
_posts/2021-03-09-gsoc2021.md
_posts/2022-03-02-NF-CDR-Interview-Call.md
index.md
pages/conduct.md

fix #225 
- top level pages (landing page)
- static pages (Code of Conduct, see also https://github.com/MDAnalysis/mdanalysis/pull/3567 for the primary copy)
- blog posts

fix section levels

---

_posts/2022-05-27-gsoc-students.md

Hi all, I have never opened a PR against a PR, hope this was the correct way to do it... Please let me know if I should add my changes in a different way.

Added Bjarne's post.

---

_posts/2022-05-27-gsoc-students.md

I have updated my intro hope its good

Aya's introduction

---

__posts/2022-06-02-release-2.2.0.md

Template blog post for version 2.2.0 release (currently largely empty, details tba)

blog post to announce 2.2.0

---

_posts/2022-07-29-junior-dev-job.md

Junior dev post

---

_posts/2022-08-22-mdakits-intro.md

fix #241 
Blog post for the release of the white paper. 
* announce white paper
* summarize MDAKits
* ask for feedback

MDAKits post

---

_posts/2022-08-24-mdakits-intro.md

- updated date to today
- link fix
- final call to action

fixes to blog post

---

_config.yml

Made the website tagline match our GitHub tagline https://github.com/MDAnalysis/

updated description/tag line

---

_config.yml
_posts/2022-11-02-relicensing.md

Opening this so we can cherry pick proposed changes.

[WIP] Licensing blog edits

---

_posts/2022-11-02-relicensing.md
_posts/2022-11-07-relicensing.md

relicensing blog post

---

_posts/2022-12-6-uma_outreachy.md

Outreachy Blog Post 

---

_posts/2022-12-15-gsoc_outreachy2022-final.md

Chnges the date for GSOC summary post to today.

move post date for GSOC summary.

---

pages/conduct.md

- add option to report to NF conduct
- makes CoC consistent with https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-Onboarding-Guide-2023
This PR can be merged once https://github.com/MDAnalysis/mdanalysis/pull/4135 is merged (the original source doc).

add reporting to NF to CoC

---

about.md

- @RMeli was elected as a new coredev
- add to list of coredevs

add new coredev

---

pages/conduct.md

I will merge this PR immediately, since it is just a copy/paste of the CoC updates that were approved in https://github.com/MDAnalysis/mdanalysis/pull/4289 and https://github.com/MDAnalysis/mdanalysis/pull/4298

Copying updates from main code repository

---

_posts/2023-09-22-licensing-update.md

Relicensing update post - towards LGPLv2.1

---

.github/workflows/build_page.yaml

Fixes #327 
TODO:
- This probably needs some kind of workflow_dispatch..

Add page build action

---

pages/privacy.md

Update goatcounter policy

---

.github/workflows/build_page.yaml

Not sure why it wasn't seen earlier, but hopefully this should fix it.

Fix broken upload-pages-artifact action

---

_config.yml
_data/team/roles/community_engagement.yml
about.md
pages/conduct.md
pages/installation_quick_start.md
pages/learning_MDAnalysis.md
pages/mdakits.md

I did not change the links in the old blog posts. Should I?

Swap mailing lists with GitHub Discussions

---

_posts/2024-01-04-release-2.7.0.md

Largely copied from the release notes (+ the previous blog posts)

Blog post for version 2.7

---

about.md

Fixes https://github.com/MDAnalysis/MDAnalysis.github.io/issues/299 and addresses conversations related to transparency about who is paid by grants as it relates to roles and responsibilities
Key personnel across grants (@fiona-naughton, @IAlibay, @lilyminium, @micaela-matta, @orbeckst, @richardjgowers) should please confirm their grant information is represented properly. @orbeckst - I especially wasn't sure how to best represent the NSF funding here.
Since many of the SDGs were awarded to MDAnalysis before it became a NumFOCUS sponsored project, I do not have access to historical records about key personnel involved on these grants. Please add if you know any of this information.

Add funding information to website

---

pages/ugm2024.md

This will be updated as we start to finalize details, but it would be good to start having a place that we can work off of and direct people to.
@richardjgowers - when you have a chance, do you think you could add a nice new UGM 2024 banner here? 0:)

Add new page for UGM 2024

---

about.md

@lilyminium - I'm so sorry that I missed this back when you first opened https://github.com/MDAnalysis/MDAnalysis.github.io/pull/343, but I had a closer look at this section when I was updating the funding information. I've made a couple of minor suggestions here to improve the clarity of the wording.

Minor suggestions for 'Feedback' paragraph

---

_config.yml

- fix #361 
- fix link to development forum

fix forum links

---

.github/workflows/build_page.yaml

Update GitHub actions

---

_data/team/roles/non_core_library_maintenance.yml

This PR fixes some punctuation that was invalid for yaml parsing.

Fix site build

---

_data/team/roles/community_engagement.yml
_data/team/roles/continuous_integration.yml
_data/team/roles/core_library_maintenance.yml
_data/team/roles/documentation.yml
_data/team/roles/outreach.yml
about.md

Add Egor to coredevs list and teams page

---

_posts/2024-05-27-gsoc-outreachy-students.md
_posts/2024-08-30-gsoc2024-final-sm.md
_posts/2025-02-11-gsoc2024-final-lg.md
about.md
index.md
pages/installation_quick_start.md
pages/learning_MDAnalysis.md
pages/mdakits.md

FIX broken links

---

pages/community.md

This PR addresses https://github.com/MDAnalysis/MDAnalysis.github.io/issues/441.

add community page

---

pages/events.md

add hackathons to events page
